# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mario's Website
masthead_title: Mario Theuermann
email: mario@theuermann.dev
description: >- # this means to ignore newlines until "baseurl:"
  Professional background and achievements of Mario Theuermann, featuring information on past roles in various industries, projects, and educational credentials.
# twitter_username:
github_username: theuema
minimal_mistakes_skin: dreck #default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  # name   : "Mario Theuermann"
  avatar : "/assets/images/bio-pic.jpg"
  bio    : "Engineering Professional with a passion for learning from data. Skilled in Bash, Python, C, C++, complemented by strong teamwork and interpersonal skills."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mario@theuermann.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theuema"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/theuema/"

footer:
  links:
    - label: "Email"
      show_label: false
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mario@theuermann.dev"
    - label: "Encrypt Email"  
      show_label: false
      icon: "fas fa-fw fa-key"
      url: "https://keys.openpgp.org/vks/v1/by-fingerprint/43F95D30A656BA79926A8EDEDBC6AD6A45A9F15A"
    - label: "GitHub"
      show_label: false
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theuema"
    - label: "Linkedin"
      show_label: false
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/theuema/"


atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
